version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: pm2-dev ./app/app.js
    environment:
      NODE_ENV: development
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT
    depends_on:
      - mariadb
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:8090
    volumes:
      - .:/usr/src/app
      - ./node_modules:/home/nodejs/node_modules

  mariadb:
    image: mariadb:10.5
    env_file: ./.env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - $MYSQL_LOCAL_PORT:3306

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    ports: 
      - "8080:8080"

volumes:
  mariadb: